# Generated by Django 3.0.7 on 2020-06-23 06:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('basic_rate', models.IntegerField(default=0)),
                ('additional_rate', models.IntegerField(default=0)),
                ('partnership', models.BooleanField(default=False)),
                ('time_weekdays', models.CharField(max_length=30)),
                ('time_weekends', models.CharField(max_length=30)),
                ('section_count', models.IntegerField(default=0)),
                ('distance', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='distance')),
            ],
        ),
    ]
