# Generated by Django 3.0.7 on 2020-06-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('basicRate', models.IntegerField()),
                ('additionalRate', models.IntegerField()),
                ('partnership', models.BooleanField(default=False)),
                ('time_weekdays', models.CharField(max_length=30)),
                ('time_weekends', models.CharField(max_length=30)),
            ],
        ),
    ]
