# Generated by Django 3.0.7 on 2020-06-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200626_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cardNum',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
